name: Modify and Sign APK with Temporary Key

on:
  push:
    paths:
      - new_config.json
      - original.apk
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Install apktool & tools
      run: |
        sudo apt-get update
        sudo apt-get install -y zipalign apksigner wget
        wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O apktool
        wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
        chmod +x apktool
        sudo mv apktool apktool.jar /usr/local/bin/

    - name: Decompile APK
      run: |
        apktool d original.apk -o output --force

    - name: Remove META-INF to avoid signature conflicts
      run: |
        rm -rf output/original/META-INF

    - name: Replace config.json
      run: |
        cp new_config.json output/assets/flutter_assets/assets/config.json

    - name: Rebuild APK
      run: |
        apktool b output -o unsigned.apk

    - name: Generate temporary keystore
      run: |
        keytool -genkey -v -keystore temp.jks -keyalg RSA -keysize 2048 -validity 10000 -alias tempkey \
          -storepass password -keypass password -dname "CN=GitHub CI,O=Example,C=US"

    - name: Sign APK with temporary key
      run: |
        apksigner sign \
          --ks temp.jks \
          --ks-key-alias tempkey \
          --ks-pass pass:password \
          --key-pass pass:password \
          --out signed.apk \
          unsigned.apk

    - name: Verify APK Signature
      run: |
        apksigner verify signed.apk

    - name: Align APK
      run: |
        zipalign -p -f 4 signed.apk final.apk

    - name: Upload Final APK
      uses: actions/upload-artifact@v4
      with:
        name: signed_apk
        path: final.apk
